// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GDTCore","status":true,"description":"","parameters":{}},
{"name":"EventCollision","status":true,"description":"","parameters":{}}
];
